version: 2.1
commands:
  deploy_netlify:
    description: 'Deploy frontend to netlify'
    parameters:
      siteId:
        type: string
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Deploy to netlify
          command: npx netlify-cli deploy -d /tmp/front-build -a $NETLIFY_TOKEN -s << parameters.siteId >> -p
  build_front:
    description: 'Build front for env'
    parameters:
      targetEnv:
        type: string
    steps:
      - setup_deps
      - run:
          name: Build frontend
          command: yarn build:<< parameters.targetEnv >>
      - run:
          name: Copy front end artifacts to workspace
          command: cp dist/myApplicationFront /tmp/front-build -r
      - store_artifacts:
          path: /tmp/front-build
      - persist_to_workspace:
          root: /tmp
          paths:
            - front-build

  setup_deps:
    description: 'Setup cache and do a yarn install'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: yarn
jobs:
  test: &test
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/myApplicationFront
    steps:
      - setup_deps
      - run:
          name: Executing tests
          command: yarn test --no-watch --no-progress --browsers=ChromeHeadlessCI || echo 'Currently failing'
  prettier:
    <<: *test
    steps:
      - setup_deps
      - run:
          name: Check prettier
          command: yarn format:check
  lint:
    <<: *test
    steps:
      - setup_deps
      - run:
          name: Check lint
          command: yarn lint
  cache:
    <<: *test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - ~/alexandrie-front/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn
  build-dev:
    <<: *test
    steps:
      - build_front:
          targetEnv: dev
  build-prod:
    <<: *test
    steps:
      - build_front:
          targetEnv: prod
  deploy-dev:
    <<: *test
    steps:
      - deploy_netlify:
          siteId: $SITE_DEV_ID
  deploy-prod:
    <<: *test
    steps:
      - deploy_netlify:
          siteId: $SITE_ID
  release:
    <<: *test
    steps:
      - setup_deps
      - run:
          name: release
          command: yarn release || true

workflows:
  version: 2
  api-front:
    jobs:
      - cache:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
      - test
      - lint
      - prettier
      - build-dev:
          filters:
            tags:
              ignore: /^v.*/
      - build-prod:
          requires:
            - go-to-prod
          filters:
            branches:
              only:
                - master
            tags:
              only: /^v.*/
      - deploy-prod:
          requires:
            - build-prod
          filters:
            branches:
              only:
                - master
            tags:
              only: /^v.*/
      - deploy-dev:
          requires:
            - lint
            - prettier
            - build-dev
          filters:
            tags:
              ignore: /^v.*/
            branches:
              only: master
      - go-to-prod:
          type: approval
          requires:
            - deploy-dev
          filters:
            branches:
              only: master
      - release:
          requires:
            - go-to-prod
          filters:
            branches:
              only: master
